### PR TITLE
Updated GUI

### PR DESCRIPTION
**Pull request by ghost**
The GUI now supports transitioning from Map Planning to Map Execution to Map Recap and then back to Planning. I fixed some of the bugs with buttons and transitioning, though there is still some work left to do.

Also, I added support for the "OLD_GUI" macro. If you go to the .pro file and follow the instructions, defining OLD_GUI and rebuilding the project reverts you back to the previous version of the GUI. This way, if someone needs to work with the old GUI, they don't need to comment out new GUI code. Simply define the OLD_GUI macro and rebuild the project.

### CODE REVIEW

**Comment by JordanD2** [comment]
I tested this on my computer. It built fine and there were no conflicts. I was able to input a mission using mouse clicks and click on the execute button, but when I clicked on Start Mission in the Execution window the program instantly crashed.

The crash report suggested the error was related to the DigitalClock class. Also the KERN_INVALID_ADDRESS implies the error was caused by attempting to access previously deallocated memory.

I can consistently reproduce the bug on my computer (Mac - OSX 10.9)

bug report

**Comment by ghost** [comment]
Fixed the Start Mission issue and currently fixing some other bugs before committing again. When I click "Start Mission", what about the GUI should I be expecting to change? It seems to work, but I don't notice any significant differences.

**Comment by ghost** [comment]
Start Mission fixed, and the transitioning is pretty fluid. Gonna work on managing memory, testing, and fixing any further bugs, like the "Exit" button one I reported.

**Comment by JordanD2** [comment]
Ok, the StartMission bug is definitely fixed, and this iteration can interface correctly with the Simulation just like before. Now there's a bug where the red line that to tracks the position of the UAV no longer draws as the telemetry points stream in, and the mouse listener that allows you you add points in mission planning is still enabled in mission execution.

**Pull request merged**
